apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  MYSQL_USER: {{ .Values.configmap.data.MYSQL_USER }}
  MYSQL_DATABASE: {{ .Values.configmap.data.MYSQL_DATABASE }}
  