apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mysql-deployment
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-mysql
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-mysql
    spec:
      containers:
        - name: {{ .Release.Name }}-mysql
          image: {{ .Values.mysql.deployment.images }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: ROOT_PASSWORD
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: USER_PASSWORD
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-configmap
                  key: MYSQL_USER
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-configmap
                  key: MYSQL_DATABASE 
          ports:
            - containerPort: {{ .Values.mysql.deployment.ports.containerPort }}
          volumeMounts:
            - name: {{ .Release.Name }}-mysql-persistent-storage
              mountPath: {{ .Values.mysql.deployment.volumeMounts.mountPath }}
      volumes:
        - name: {{ .Release.Name }}-mysql-persistent-storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-mysql-persistent-volume-claim