apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-mysql-persistent-volume-claim
spec:
  accessModes:
    - {{ .Values.mysql.persistentVolumeClaim.accessModes }}
  resources:
    requests:
      storage: {{ .Values.mysql.persistentVolumeClaim.resources.requests.storage }}
