apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-react-app-service
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-react-app
  ports:
    - port: {{ .Values.reactapp.service.ports.port }}
      targetPort: {{ .Values.reactapp.service.ports.targetPort }}