apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-spring-boot-app-service
spec:
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-spring-boot-app
  ports:
    - port: {{ .Values.springbootapp.service.ports.port }}
      targetPort: {{ .Values.springbootapp.service.ports.targetPort }}